version: "1.0"
name: "smart-coworking-space-be"
services:
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/?authSource=admin
      ME_CONFIG_MONGODB_SERVER: mongodb
  mongodb:
    container_name: fodex-mongodb
    image: mongo:6.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  app:
    container_name: smart-coworking-space-api
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/usr/src/app
    args:
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
